on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Grabbing latest statistics from the repository
    steps:
      - name: Grabbing repo stats
        id: hello
        uses: /jlengrand/github-repository-stats-action@feat/grabbing-repo-stats
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          server-url: ${{ secrets.SERVER_URL }}`
      - name: Grabbing repo stats output
        run: echo "The payload is ${{ steps.hello.outputs.payload }}"
