on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Grabbing latest statistics from the repository
    steps:
      - name: Grabbing repo stats
        id: hello
        uses: /jlengrand/github-repository-stats-action@feat/grabbing-repo-stats
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Grabbing repo stats output
        run: echo "The time was ${{ steps.hello.outputs.time }}"
